// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: T4-S3

#include "../ui.h"

void ui_Speed_screen_init(void)
{
ui_Speed = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Speed, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_Speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Satellites = lv_obj_create(ui_Speed);
lv_obj_remove_style_all(ui_Speed_Satellites);
lv_obj_set_width( ui_Speed_Satellites, 130);
lv_obj_set_height( ui_Speed_Satellites, lv_pct(100));
lv_obj_set_align( ui_Speed_Satellites, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Speed_Satellites, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_Speed_SatelliteIcon = lv_label_create(ui_Speed_Satellites);
lv_obj_set_width( ui_Speed_SatelliteIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Speed_SatelliteIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speed_SatelliteIcon, 16 );
lv_obj_set_y( ui_Speed_SatelliteIcon, -157 );
lv_obj_set_align( ui_Speed_SatelliteIcon, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Speed_SatelliteIcon,"");
lv_label_set_recolor(ui_Speed_SatelliteIcon,"true");
ui_object_set_themeable_style_property(ui_Speed_SatelliteIcon, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_Speed_SatelliteIcon, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Grey);
lv_obj_set_style_text_font(ui_Speed_SatelliteIcon, &ui_font_FontAwesomeSolid, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Speed_SatelliteIcon, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Speed_SatelliteIcon, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Speed_SatelliteIcon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Speed_SatelliteIcon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_SatelliteConnections = lv_label_create(ui_Speed_Satellites);
lv_obj_set_width( ui_Speed_SatelliteConnections, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Speed_SatelliteConnections, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speed_SatelliteConnections, 0 );
lv_obj_set_y( ui_Speed_SatelliteConnections, -172 );
lv_obj_set_align( ui_Speed_SatelliteConnections, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Speed_SatelliteConnections,"5");
lv_obj_set_style_text_font(ui_Speed_SatelliteConnections, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_DirectionText = lv_label_create(ui_Speed);
lv_obj_set_width( ui_Speed_DirectionText, 400);
lv_obj_set_height( ui_Speed_DirectionText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speed_DirectionText, -54 );
lv_obj_set_y( ui_Speed_DirectionText, -156 );
lv_obj_set_align( ui_Speed_DirectionText, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed_DirectionText,"no satellites");
ui_object_set_themeable_style_property(ui_Speed_DirectionText, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Grey);
ui_object_set_themeable_style_property(ui_Speed_DirectionText, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Grey);
lv_obj_set_style_text_align(ui_Speed_DirectionText, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speed_DirectionText, &ui_font_MontserratSemiBoldLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Logging = lv_textarea_create(ui_Speed);
lv_obj_set_height( ui_Speed_Logging, 330);
lv_obj_set_width( ui_Speed_Logging, lv_pct(100));
lv_obj_set_align( ui_Speed_Logging, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_Speed_Logging,"Placeholder...");
lv_obj_set_style_text_color(ui_Speed_Logging, lv_color_hex(0x00FF11), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Speed_Logging, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Speed_Logging, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speed_Logging, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Speed_Logging, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Speed_Logging, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Speed_Logging, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Speed_Logging, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
