// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: T4-S3

#ifndef _T4_S3_UI_H
#define _T4_S3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Speed
void ui_Speed_screen_init(void);
extern lv_obj_t *ui_Speed;
extern lv_obj_t *ui_Speed_Satellites;
extern lv_obj_t *ui_Speed_SatelliteIcon;
extern lv_obj_t *ui_Speed_SatelliteConnections;
extern lv_obj_t *ui_Speed_DirectionText;
extern lv_obj_t *ui_Speed_Logging;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_FontAwesomeSolid);
LV_FONT_DECLARE( ui_font_MontserratSemiBoldLarge);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
