// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: T4-S3

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_DigitalBg[2] = {0x212121, 0x212121};
const ui_theme_variable_t _ui_theme_alpha_DigitalBg[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Grey[2] = {0x777777, 0x777777};
const ui_theme_variable_t _ui_theme_alpha_Grey[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

